[package]
name = "etive-architecture-throughput"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn.git", rev = "5c6f009585fdf3cda7ff37132f2c869d3f4c710f", default-features = false, features = ["autotune", "cuda", "fusion", "std"] }

[patch."https://github.com/tracel-ai/cubek"]
cubek = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-attention = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-convolution = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-fft = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-interpolate = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-matmul = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-pool = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-quant = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-random = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-reduce = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-std = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }
cubek-tile = { git = "https://github.com/bungogood/cubek.git", rev = "2744b9eb499d63b670727d0a1bd3d9694d7f22f7" }

[profile.release]
codegen-units = 1
lto = "fat"
